dist: xenial
language: python
python:
  - 3.6

before_install:
  - docker-compose -f docker/docker-compose.yml up -d
  - sleep 10

install:
  - docker exec -it qgis bash -c 'cp /shared/ttf/*.ttf /usr/share/fonts/'
  - docker exec -it qgis bash -c 'fc-cache -f -v'
  - docker exec -it qgis bash -c 'apt-get update && apt install -y inkscape zip'

script:
  - docker exec -it qgis /bin/bash -c -l -i 'cd /shared/scripts && ./build.sh'

deploy:
  provider: releases
  api_key:
    secure: H8nDIwFCdKAuBPu/1Wgvut2IMvZYfJgjBvh4NaE2+6O6697cPg8wK/W1XJbP0TO258FNYRgQohn9w9ye9PJV4fDTRmaulQLo7/3KmDKVxB62EFAmetwocfGYkT8Yo8l4r0axz/OCddIcSofPHRYdAoKgsESKmR1Iiblx6vPUkUsD/5pNj+EnPrvv6STmaoTb9axj8/uCfh4ZXy2EpbVmnEeesLdkFKnIQdJG0rOA2ZDjDCamT2mNVlfaSMtkJoWZdezhiABZ7HxIFZ0e7JqO4Fw5ec9CfyQVPZWhRdKWIjc8KRgYiAzWhiOshFt23QZ3RGXEfSZ5eKn8iaOSAFGJ67pez0o+92+PrgS0JqRSdFEzcG8oDjrJ1I1MRvvE1y37mMXoYeQNggafuQHtTOChQOVlDvai4g0/B7Whinyg58x+a0yveTylyVrC9g9vAty8aM9o8mLfW+9H49iKzmUYKzYlRLOj1sQP7EmS4S4XDNDb7X6mcc6XlHg4M0H4FTZG8GvvjivDD/pxmxdily+E6/ZqCqiY3Egnox5JeOjYf/pjAu8L1Pfp/FDYnfe3mU9ekmt6Ny8vSVjoxQm6m5D40szk1ZVhehEKl2WkKb7jQq3YJHiQHGy6oIaxhyWulCHnOjDyM/cgGeZuB+qL7qW64nAW9FewXu13qzYOsk0qJ/k=
  file: result/libreria.zip
  on:
    tags: true

notifications:
  email: false

