* Symbology-ti
** Engineering
*** Functional Requirements
**** FR1 Xml library
     The result shall include a QGIS style library xml file containing the 1203
     ESRI symbols converted.
     - Rationale
       To not be dependent of ESRI and to conform to OGC.
     - Fit criterion
       A QGIS's style xml file containing a QGIS symbol for all the 1203 original
       ESRI symbols is into the result product.
**** FR2 QGIS project
     The result shall include a QGIS project showing all the symbols.
     - Rationale
       To be able to look the rendering of all the symbols.
     - Fit criterion
       A QGIS project with at least a geometry drown with each symbol is into the
       result product.
**** FR3 png files
     The result shall include a png image of all symbols.
     - Rationale
       These png are to be used into pdf documents
     - Fit criterion
       A zip folder with a png for each symbol is into the result product.
**** FR4 png quality
     The png images shall be 6x3mm and 300dpi at least and represent correctly
     the symbol.
     - Rationale 
       To ensure a good quality of the documents using this images
     - Fit criterion
       --
**** FR5 Conversion of dimensions
     The point units of the ESRI symbols are to be converted in 0.35mm in QGIS.
     - Rationale 
       In QGIS the unit point doesn't exist
     - Fit criterion 
       --
**** FR6 Font ESRI
     Characters using ESRI fonts are to be converted in svg images.
     - Rationale 
       To not be forced to install new fonts on the user computers.
     - Fit criterion
       All character of ESRI fonts are converted into a svg image.
** XML library
*** Requirements
    - QGIS3 in python path
    - Inkscape
*** Creation
    #+BEGIN_SRC sh
      cd ti-utils/
      python library.py
    #+END_SRC
*** Installation in QGIS2
    - In =Options - System - SVG Paths=, add the path of the svg directory.
    - Optional
      - Create a new group in Style manger e.g. libreria
    - In =Style Manager - Import=, import the xml =libreria.xml= file.
      - (optional) save into group libreria
      - Select all
      - Import 
